PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?item ?img WHERE {{
  VALUES ?anotherItem {{ <{}> }}
  ?item edm:isShownBy ?img.
  OPTIONAL {{
    ?item edm:rights|dc:rights ?rights .
  }}
    ?item dct:created ?created .
    ?anotherItem dct:created ?created .
  # BIND (IRI(?obj) AS ?img)
  FILTER (?anotherItem != ?item)
  FILTER (contains(?rights, "CC"))
}} LIMIT 5